---
roles:
  - name: gantsign.oh-my-zsh
    src: https://github.com/gantsign/ansible-role-oh-my-zsh
    version: 2.2.1
  - name: stouts.nginx
    src: https://github.com/Stouts/Stouts.nginx
    version: 2.1.2
  # - name: gavika.openvpn 
  #   src: https://github.com/gavika/openvpn
  #   version: v1.1.0
  # - name: gavika.easy_rsa
  #   src: https://github.com/gavika/easy_rsa
  #   version: v1.0.0
  - name: geerlingguy.docker
    src: https://github.com/geerlingguy/ansible-role-docker
    version: 2.7.0
  - name: stouts.openvpn
    src: https://github.com/Stouts/Stouts.openvpn
    version: develop
  - name: nkakouros.easyrsa
    src: https://github.com/nkakouros-original/ansible-role-easyrsa
    version: master
  - name: stouts.sudo
    src: https://github.com/Stouts/Stouts.sudo
    version: 2.1.1
  - name: stouts.users
    src: https://github.com/Stouts/Stouts.users
    version: 1.2.1
