---
- hosts: homeserver
  roles:    
    - community/stouts.users
    - community/gantsign.oh-my-zsh
  vars:
    sys_packages: [ 'curl', 'git', 'ufw']
    oh_my_zsh_theme: gnzh
    oh_my_zsh_plugins: [docker, encode64, git, httpie, zsh-autosuggestions, zsh-syntax-highlighting]
    users:  # oh-my-zsh
      - username: ujlbu4  # TODO: replace with users from group_vars
  tasks:
    - name: Update apt
      apt: update_cache=yes state=latest
    - name: Install required system packages
      apt: 
        name: "{{ sys_packages }}"
        state: present

    # UFW Setup
    - name: UFW - Allow SSH connections
      ufw:
        rule: allow
        name: OpenSSH

    - name: UFW - Deny all other incoming traffic by default
      ufw:
        state: enabled
        policy: deny
        direction: incoming