---
- hosts: homeserver
  roles:
    - openvpn
  tasks:
    - name: Display all variables/facts known for a host
      debug:
        var: hostvars[inventory_hostname]
        verbosity: 4
    # UFW Setup
    - name: UFW - Allow openvpn connections
      ufw:
        rule: allow
        proto: udp
        to_port: 1194