# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # boxes: https://app.vagrantup.com/boxes/search
  config.vm.box = "ubuntu/bionic64" # Ubuntu 18.04 LTS

  config.vm.hostname = "homeserver.v"
  config.vm.network "private_network", ip: "172.16.20.10"
end
