---
- hosts: homeserver
  become: true
  vars:
    doc_root: /var/www/example
  tasks:
    - name: Update apt
      apt: update_cache=yes
    - name: Install zsh
      apt: 
        name: ['git', 'zsh']
        state: latest
    - name: Check zsh is installed 
      shell: zsh --version
      register: zsh_installed
      become: false
    - name: Backing up existing .zshrc
      shell: if [ -f ~/.zshrc ]; then mv ~/.zshrc{,.orig}; fi
      when: zsh_installed is success
      become: false
    - name: Cloning oh-my-zsh
      git:
          repo=https://github.com/robbyrussell/oh-my-zsh
          dest=~/.oh-my-zsh
      when: zsh_installed is success
      register: ohmyzsh_cloned
      become: false
    - name: Creating new ~/.zshrc
      copy:
        src=~/.oh-my-zsh/templates/zshrc.zsh-template
        dest=~/.zshrc
      when: ohmyzsh_cloned is success
      become: false
